### PR TITLE
Fix for Directory Ordering compare function.

### LINKED ISSUE #60: Garbage `DirEntry`
I'm currently hitting what seem to be garbage `DirEntry` entries, which lead to some strange errors.

```
[src/internal/directory.rs:156:50] &entry.name = "WordDocument"
[src/internal/directory.rs:156:69] &dir_entry.name = "\u{5}SummaryInformation"
[src/internal/directory.rs:156:50] &entry.name = "\u{1}CompObj"
[src/internal/directory.rs:156:69] &dir_entry.name = "WordDocument"
[src/internal/directory.rs:156:50] &entry.name = "1Table"
[src/internal/directory.rs:156:69] &dir_entry.name = "\u{1}CompObj"
[src/internal/directory.rs:156:50] &entry.name = "ÄTHEOÖGIÝU0×1GK0VLO×ÌQ=="
[src/internal/directory.rs:156:69] &dir_entry.name = "ÖÇÔÍÒÄÁØÐÔÞ3×ÆXVÔÄHMDQ=="

thread 'tests::t_cfb_sectors' panicked at src/lib.rs:1134:78:
called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidData, error: "Malformed directory (name ordering, \"ÖÇÔÍÒÄÁØÐÔÞ3×ÆXVÔÄHMDQ==\" vs \"ßYÜ0MÈÝEÄÄÂKÏÓÉDÀP5ÃÝA==\")" }
```

I've attached a testcase. Any intuition or hunch what might be causing this?

[name_error.txt](https://github.com/user-attachments/files/20986813/name_error.txt) (had to rename to .txt to be able to upload, but original extension is .doc)

### PR DESCRIPTION
**Pull request by TheSchemm**
Fixes #60 

This is caused by the way that Rust does case folding. Rust does full case folding where the MS-CFB spec states that simple case folding should be used.
Because of the full case folding:
`ßQÑ52Ç4ÅÁÔÂFÛCWCÙÂNË5Q==` becomes `SSQÑ52Ç4ÅÁÔÂFÛCWCÙÂNË5Q==` where the `ß` should remain unchanged when using simple case folding.

This imports the icu_casemap crate that can do the simple case folding. I also made it so that string compares don't allocate new strings.

### CODE REVIEW

File: src/internal/path.rs [hunk 1]
```diff
@@ -128,6 +135,15 @@ mod tests {
...
 
+    #[test]
+    fn test_uppercase() {
+        
+        let uppercase = "ßQÑ52Ç4ÅÁÔÂFÛCWCÙÂNË5Q==".chars().map(cfb_uppercase_char).collect::<String>();
+        assert_eq!("ßQÑ52Ç4ÅÁÔÂFÛCWCÙÂNË5Q==", uppercase);
+
+        assert_eq!(compare_names("ÜL43ÁMÆÛÏEKZÅYWÚÓVDÙÄÀ==", "ßQÑ52Ç4ÅÁÔÂFÛCWCÙÂNË5Q=="), Ordering::Less);
+    }
+
```
Comment (sftse) [inline src/internal/path.rs:146]:
```suggestion
        let uppercase = "ßQÑ52Ç4ÅÁÔÂFÛCWCÙÂNË5Q==".chars().map(cfb_uppercase_char).collect::<String>();
        assert_eq!("ßQÑ52Ç4ÅÁÔÂFÛCWCÙÂNË5Q==", uppercase);

        assert_eq!(compare_names("ÜL43ÁMÆÛÏEKZÅYWÚÓVDÙÄÀ==", "ßQÑ52Ç4ÅÁÔÂFÛCWCÙÂNË5Q=="), Ordering::Less);
    }

```

**Comment by sftse** [comment]
Thanks, that clears things up.

**Comment by mdsteele** [comment]
Ah, that makes sense.  Thanks for figuring this out.

**Comment by mdsteele** [comment]
Thanks, looks good to me; just need to make clippy happy.  (Either by taking its suggestion, or by [suppressing](https://github.com/rust-lang/rust-clippy#allowingdenying-lints) the warning for the sake of the TODO; either way seems fine to me.)

File: src/internal/path.rs [hunk 2]
```diff
@@ -1,27 +1,26 @@
...
+/// using simple capitalization and the ability to add exceptions.
+/// Used when two directory entry names need to be compared.
+fn cfb_uppercase_char(c: char) -> char {
+    match c {
+        // TODO: Edge cases can be added that appear
+        // in the table from Appendix A, <3> Section 2.6.4
+
+        // Base case, just do a simple uppercase
+        _ => CASE_MAPPER.simple_uppercase(c),
     }
```
Comment (sftse) [inline src/internal/path.rs:23]:
```suggestion
    // TODO: Edge cases can be added that appear
    // in the table from Appendix A, <3> Section 2.6.4

    // Base case, just do a simple uppercase
    CASE_MAPPER.simple_uppercase(c)
```
